2 Tests for MoodPanda
olgaKudina/MoodPanda pull request #1
Opened 2021-06-09 20:39 UTC by olgaKudina

2021-06-11 14:58 UTC, vchesnakoutest requested changes
please make fixes and merge

2021-06-11 14:58 UTC, vchesnakoutest commented on src/main/java/pages/IConstants.java
> +    public static String PASSWORD = "123456";
класс с константами логина и паролей должны лежать в Src/test/java - т.к. это тестовые данные

2021-06-11 14:58 UTC, vchesnakoutest commented on src/main/java/pages/MyDiaryPage.java
> +    public String getText() {
getBadgeText

2021-06-11 14:58 UTC, vchesnakoutest commented on src/main/java/pages/MyUpdatesPage.java
> +        $(INPUT_REPLY_CSS).sendKeys("Have a good Day");
"Have a good Day" - это тестовые данные , лучше их передавать из теста, а в этом методе сделать параметр, кот. этот текст будет принимать

2021-06-14 18:47 UTC, olgaKudina reviewed
Fixes done.

2021-06-14 18:48 UTC, merged